{
    "token": 'THRwDWc9hiNEyPK9Z4UdavB1PNy1K66Z4OrjgTi1uSHSg4k5FC8VvsxCVfB85zwhG82Vfp4AkMJeounnESKNB5Y8PnGpFzYq9J9XVZ2GqkkEodp6_G7pSZLJ',
    "study_id": '67921799e74faff79f868e94',
    "max_concurrent_sessions": 50,
    "workload_checker_period": 60
}